// REQUEST REPOS FROM GITHUB REST API
export const BEGIN_REPOS_REQUEST = "BEGIN_REPOS_REQUEST";
export const SUCCESS_REPOS_REQUEST = "SUCCESS_REPOS_REQUEST";
export const FAIL_REPOS_REQUEST = "FAIL_REPOS_REQUEST";
export const SET_REPOS_LIST = "SET_REPOS_LIST";
export const RESET_REPOS_STATE = "RESET_REPOS_STATE";
export const HAS_MORE_REPO = "HAS_MORE_REPO";

// REQUEST USER FROM GITHUB REST API
export const BEGIN_USER_REQUEST = "BEGIN_USER_REQUEST";
export const SUCCESS_USER_REQUEST = "SUCCESS_USER_REQUEST";
export const FAIL_USER_REQUEST = "FAIL_USER_REQUEST";
export const SET_USER = "SET_USER";
