name: CI/CD

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: asia-east1
  SERVICE_NAME: github-repo-search-react

jobs:
  ci-node:
    runs-on: ubuntu-latest
    name: CI Node ${{ matrix.node }}
    strategy:
      matrix:
        node: [ '16' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn
#      - name: Unit tests
#        run: yarn test
#      - name: ESLint
#        run: yarn eslint src/*.js
      - name: Build
        run: yarn build
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build

  e2e-on-chrome:
    needs: [ ci-node ]
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v3
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome

  e2e-on-firefox:
    needs: [ ci-node ]
    runs-on: ubuntu-latest
    name: E2E on Firefox
    container:
      image: cypress/browsers:node16.13.2-chrome100-ff98
      options: --user 1001
    steps:
      - uses: actions/checkout@v3
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: firefox

#  e2e-on-edge:
#    needs: [ ci-node ]
#    runs-on: windows-latest
#    name: E2E on Edge
#    steps:
#      - uses: actions/checkout@v3
#      - name: Download the build folders
#        uses: actions/download-artifact@v3
#        with:
#          name: build
#          path: build
#      - uses: cypress-io/github-action@v2
#        with:
#          start: yarn start
#          wait-on: "http://localhost:3000"
#          wait-on-timeout: 120
#          browser: edge

  cd-gcp:
    needs: [ci-node, e2e-on-chrome, e2e-on-firefox]
    runs-on: ubuntu-latest
    name: CD GCP
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GCP Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Use gcloud CLI
        run: gcloud info
      - name: Build Docker image
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "asia.gcr.io/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA"
      - name: Deploy GCR
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "asia.gcr.io/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated

